### PR TITLE
Add link to electron-installer-windows

### PR DESCRIPTION
**Pull request by fcastilloec**
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] The changes are appropriately documented (if applicable).
* [x] The changes have sufficient test coverage (if applicable).
* [x] The testsuite passes successfully on my local machine (if applicable).

**Summarize your changes:**
Add a link to `electron-installer-windows` project to the README

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
I'm somewhat confused as to the difference between this and the officially maintained (and already linked) `electron-winstaller`?  Can you explain the differences?

**Comment by fcastilloec** [comment]
`electron-winstaller` is only partially maintained, they only update Squirrel once in a while. There are no test suites, they are not using the latest version of Nuget and it doesn't work on Linux/OSX systems using `mono`/`wine`.
Also, in a project I was contributing, `electron-winstaller` installers were creating errors on installation (see https://github.com/headsetapp/headset-electron/issues/129) which I could replicate with other projects.

On the other hand, `electron-installer-windows` has tests, works in all OSs without any problems (signing the installer is only supported on Windows), it has a CLI, and it has a familiar form, similar to the already used `electron-installer-debian`, `electron-installer-redhat`, etc.

I think it's better to provide users more alternatives, especially if the new alternative works better and in all OSs.
I understand if there's a motivation to only keep one option, or to advertise a specific module, feel free to close this PR.

**Comment by fcastilloec** [comment]
`electron-winstaller` doesn't work for me and a lot of other people according to the issues' page. This is especially true if using Linux or OSX, even all testing for Travis-CI has been removed.
I completely understand why not trusting a project that includes compiled binaries, you might not know where they come from. I'm familiar with `electron-installer-windows` so I'm probably going to push a PR there that downloads the `.zip` directly from Github releases when installing with `npm`. That way users are always sure where things come from. You should consider doing the same for `electron-winstaller`.

I love contributing to projects, but sometimes I need things to "just work". I had so much trouble with `electorn-winstaller`, I actually did try to debug the problem but wasn't getting anywhere as you can see on the link I previously posted. It was taking too much of my time so I switched to `electron-installer-windows`. I would love to try to fix the issues but it will require a lot of time that currently, I don't have. Perhaps in the future.

I think I'll rest my case and like I mentioned originally, feel free to close this PR if you think it's better that way. I really don't mind.

**Comment by malept** [comment]
I'm just going to take this. I made a few changes that differentiates the two links.

**Pull request merged**
