### PR TITLE
Drop Node < 4 support

### PR DESCRIPTION
**Pull request by malept**
Removes a polyfill module and lets us use template strings.

### CODE REVIEW

**Comment by malept** [comment]
I'll merge this in a couple of days (after I obviously fix some merge conflicts and squash) if there are no objections.

**Comment by kfranqueiro** [comment]
Does this mean the next tagged version would end up being 7.0.0, or are you thinking of allowing this to go into a minor release (presumably not patch)?

**Comment by malept** [comment]
The next release will be [7.0.0](https://github.com/electron-userland/electron-packager/milestones/7.0.0).

**Comment by kfranqueiro** [comment]
Oh hey look at that milestone over there.  In that case, sounds good to me.

**Pull request merged**
