### PR TITLE
Upgrade to electron-download@3.0 for SHASUM256.txt checking

### PR DESCRIPTION
**Pull request by kevinsawicki**
**Have you read the [section in CONTRIBUTING.md about pull requests](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#filing-pull-requests)?**

Yes

**Summarize your changes:**

Upgrade to `electron-download@3.0` which includes `SHASUM256.txt` checking.

Refs https://github.com/electron-userland/electron-download/pull/25

**Are your changes appropriately documented?**

None needed.

**Do your changes have sufficient test coverage?**

Yes

**Does the testsuite pass successfully on your local machine?**

Yes

### CODE REVIEW

**Comment by malept** [comment]
Ha, you got to it before me 😃

**Comment by malept** [comment]
Dammit, I jumped the gun on this:

https://travis-ci.org/electron-userland/electron-packager/jobs/161196771#L815-L833

**Comment by malept** [comment]
Interestingly enough, this *only* happens on the OSX workers.

**Comment by kevinsawicki** [comment]
> Interestingly enough, this only happens on the OSX workers.

Looking into this now, I think it is possibly related to the `nugget` upgrade in `electron-download` which seems to have some bug or issue on macOS Travis workers where the download progress bar runs out of memory.

**Pull request merged**
