### PR TITLE
API docs: asar-unpack can use glob syntax

### PR DESCRIPTION
**Pull request by MathijsvVelde**
Asar unpack multiple directories is possible.

Edit if you like... 👍

### CODE REVIEW

**Comment by malept** [comment]
I don't understand. This documentation seems to be for the `asar` script, not using `electron-packager` directly.

**Comment by MathijsvVelde** [comment]
Sorry about that.
Is this better?

**Comment by malept** [comment]
I think this a bit too verbose. A sentence that states that you can use glob syntax to specify multiple directories (and perhaps one example of this) is sufficient.

**Comment by MathijsvVelde** [comment]
there, Better?

**Comment by malept** [comment]
That's better, thanks.

Regarding `**/{sub_dir1/sub_sub_dir,sub_dir2}/*`:

* Is the trailing `/*` necessary?
* Would this pattern also match `/<dir>/parent_dir/sub_dir2`?

**Comment by MathijsvVelde** [comment]
It's even worse due to how asar works at this moment.
I'm gonna make a PR to fix that later.

##### `asar-unpack-dir`
 		 
_String_
 		 
Unpacks the dir to `app.asar.unpacked` directory whose names exactly or pattern match this string. The `asar-unpack-dir` is relative to `dir`.

Some examples:

- `asar-unpack-dir=sub_dir` will unpack the directory `/<dir>/sub_dir`
- `asar-unpack-dir=**/{sub_dir1/sub_sub_dir,sub_dir2}/*` will unpack the directories `/<dir>/sub_dir1/sub_sub_dir` and `/<dir>/sub_dir2`, but it will note include their subdirectories.
- `asar-unpack-dir=**/{sub_dir1/sub_sub_dir,sub_dir2}/**` will unpack the subdirectories of the directories `/<dir>/sub_dir1/sub_sub_dir` and `/<dir>/sub_dir2`.
- `asar-unpack-dir=**/{sub_dir1/sub_sub_dir,sub_dir2}/**/*` will unpack the directories `/<dir>/sub_dir1/sub_sub_dir` and `/<dir>/sub_dir2` and their subdirectories.

**Comment by malept** [comment]
As it currently stands, this PR has too many unrelated changes to it, so I'm not inclined to merge it until just the glob syntax changes remain. For more information on our pull request policy, please see: https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#filing-pull-requests

**Comment by MathijsvVelde** [comment]
I made a new pull request: https://github.com/electron-userland/electron-packager/pull/347

**Pull request closed without merging**
