### PR TITLE
Infer win32metadata from package.json/top-level options

### LINKED ISSUE #297: Package name vs. Product name
Hi, thank you for great tool.

Is there a way to package with a name that is not `productName`?
electron-packager-6.0.0 seems to naming with `productName` like `productName.app` or `productName.exe`.
I want to specify a human-readable product name that might be long and it might include space, comma, etc,.

As actual example, "Microsoft Office Word" is specified as product name to `WINWORD.EXE`.

I specified `name` option and `version-string.ProductName` option for Windows, then `name.exe` that has `ProductName` as file property was created. This result has come up to my expectations.
But, `CFBundleDisplayName` and `CFBundleName` fields for OS X were set `name`. I want to set `productName` to these.

### LINKED ISSUE #611: win32metadata should have sensible defaults
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

`win32metada` should have reasonable defaults so that Squirrel shortcut creation works out of the box as expected.

Currently, https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#win32metadata defaults to an empty object AFAIK and therefore the default metadata from Electron is left intact.

This results in lots of questions like "Why is my Squirrel shortcut called 'Electron'?".  This can be solved by simply providing logical defaults for the `win32metadata` option as follows below. Where "p" === "package.json"

| Key | Mapped Value |
|-----|-----------------|
| ProductName | `config.name or p.productName or p.name` |
| InternalName | `config.name or p.productName or p.name` |
| OriginalFilename | `config.name or p.productName or p.name` |
| FileDescription | `p.description` |
| CompanyName | `p.author` |

This is just a proposal, feedback on this welcome 👍

### PR DESCRIPTION
**Pull request by malept**
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] The changes are appropriately documented (if applicable).
* [x] The changes have sufficient test coverage (if applicable).
* [x] The testsuite passes successfully on my local machine (if applicable).

**Summarize your changes:**

Closes #297.
Fixes #611.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Was reading through this before you even summoned my review 👍 LGTM 🚢

**Comment by MarshallOfSound** [comment]
Actually hold up a second, just checking something

**Comment by MarshallOfSound** [comment]
After a quick check of 30 of my installed applications on my Windows machine 27 of them set `FileDescription` to be the same as `ProductName` and the other 3 are close just missing some symbols / spacing.

Perhaps it's worth reconsidering that default, not sure why but everyone else seems to be doing it 😕

**Comment by develar** [comment]
> Perhaps it's worth reconsidering that default, not sure why but everyone else seems to be doing it

Because on bloody windows `FileDescription` is used as app name in the process view. And if you will use description instead of name — you will get user reports. Details — https://github.com/electron-userland/electron-builder/pull/965

**Comment by MarshallOfSound** [comment]
Haha, thanks @develar 

That actually reminds me when I had that problem before...  That's windows for ya...  @malept should probably change it to be `productName || name` then 😄

**Comment by develar** [comment]
Be aware that you must normalise version string according to *** MS Windows requirements, otherwise Squirrel.Windows will be not happy and it can leads to crash — https://github.com/electron-userland/electron-builder/issues/1101#issuecomment-272644202

**Comment by malept** [comment]
If there aren't any more concerns about this PR, I'll merge it.

**Pull request merged**
