### PR TITLE
Move asar options to sub-parameters passed through asar-options

### PR DESCRIPTION
**Pull request by robfuscate**
This will let us pass an ordering file to the asar process.

### CODE REVIEW

**Comment by robfuscate** [comment]
The asar readme doesn't mention this option, but the changelist where it was added is here https://github.com/electron/asar/pull/52

**Comment by malept** [comment]
> The asar readme doesn't mention this option

😞 Someone should fix that.

As a general comment to this PR, I am not opposed to this (given that there are docs added and possibly tests), but I'd rather have all of the asar options work like `version-string`, `osx-sign`, and now `download`, that is, grouped as sub-parameters. Obviously this would mean a major version bump, since there would be a breaking parameter change to `asar`.

**Comment by robfuscate** [comment]
By moving things to asar-options, we've essentially made it so you can pass arbitrary flags to asar. I've renamed the pull request.

**Comment by malept** [comment]
It would be nice if `asar-options` was merged into `asar` - that is, `asar` can be either `true` or an object of options.

Also,  you should keep the existing `asar-unpack`* documentation and mark it deprecated (as I've done for `strict-ssl`, etc.)

**Comment by malept** [comment]
There should also be tests to make sure that `asar` options override the deprecated `asar-unpack`, etc. options.

**Comment by malept** [comment]
Continued in #417.

**Pull request closed without merging**
