### PR TITLE
Add extraResource support to all platforms

### LINKED ISSUE #637: Add extraResource support for Windows/Linux targets
Hello,
i try to copy the binary outside asar, i launch this commande line : 
`electron-packager . --out=compiledBinary/win --platform=win32 --arch=ia32 --extraResource=\"aria2\" --asar=true`

when i go to compiledBinary/win/application/Resources i don't have the folder aria2
but i try to generate for osx it's work perfectly

could you help me ?
it's a bug ?
best regards

### PR DESCRIPTION
**Pull request by malept**
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] The changes are appropriately documented (if applicable).
* [x] The changes have sufficient test coverage (if applicable).
* [x] The testsuite passes successfully on my local machine (if applicable).

**Summarize your changes:**

Fixes #637.

### CODE REVIEW

**Comment by unindented** [comment]
@malept Any idea of when you'll release a version to npm with this fix?

**Comment by malept** [comment]
@unindented probably either this weekend or next weekend. I've made several fairly large changes and I've been seeing what happens if I update certain repos that use Packager directly or indirectly.

**Comment by unindented** [comment]
Ok cool. Thank you for your work!

**Comment by malept** [comment]
@unindented in the meantime, if you could use master and see if `extraResource` breaks for you, I'd appreciate the feedback.

**Comment by unindented** [comment]
Tried using master and everything worked fine. Files appear correctly in the `resources` folder on Windows, and in the `Resources` folder on macOS. Our app is not trivial, so you should feel a bit more confident. 😁

**Pull request merged**
