### PR TITLE
update fs-extra to 0.28

### PR DESCRIPTION
**Pull request by develar**

### CODE REVIEW

**Comment by malept** [comment]
Any particular reason why?

**Comment by develar** [comment]
Because `0` in the version means that `0.27` and `0.28` versions are not meet current range. Since electron-builder uses `0.28`, user gets two copy of `fs-extra`.

**Comment by malept** [comment]
I'm aware of how semantic versioning works. I'm pretty sure the last time I looked at `npm list` for electron-packager, there were several packages with multiple versions installed.

So the only reason is to have it be the same version as electron-builder?

**Comment by develar** [comment]
> So the only reason is to have it be the same version as electron-builder?

Yes, no strong reasons. Just keep deps up to date to avoid issues like https://github.com/electron/node-mksnapshot/pull/7

**Comment by malept** [comment]
Fair enough. In the future, putting that in the PR summary would be recommended. (I still need to figure out the best thing to put in the pull_request_template.md.)

**Pull request merged**
