### PR TITLE
Add FreeBSD support

### PR DESCRIPTION
**Pull request by jbenden**
Added FreeBSD support; by way of copying Linuxes operations.

### CODE REVIEW

**Comment by malept** [comment]
I'm confused, I don't see a FreeBSD build in the Electron GitHub releases.

**Comment by develar** [comment]
[electron-builder](https://github.com/electron-userland/electron-builder) produces `appimage` for Linux and it works on FreeBSD. So, not clear for me too.

**Comment by malept** [comment]
@jbenden thank you for the pull request, however, the Electron project does not support FreeBSD-specific builds. Electron Packager only supports target platforms and architectures that upstream Electron supports. You should be able to use Linux builds using FreeBSD's [Linux binary compatibility](https://www.freebsd.org/doc/handbook/linuxemu.html) feature. If you would like to have native FreeBSD builds of Electron, please file an issue at the [Electron](https://github.com/electron/electron) issue tracker.

**Comment by jbenden** [comment]
Not so fast, please. I am in progress of getting everything (all NPMs and related) building and functioning on FreeBSD. As part of this process, I really need the change accepted - please.

Thank you.

**Comment by malept** [comment]
I will be happy to reopen when upstream Electron provides official support for prebuilt FreeBSD binaries. Until then, I can't accept this change as these changes will lack test coverage, and more importantly, Packager will incorrectly advertise that it supports creating native FreeBSD bundles.

**Comment by jbenden** [comment]
Ok, I appreciate your kind explanation. I also accept that explanation! ;)

Thank you for your time and patience...

**Comment by malept** [comment]
When this PR is ready again, it would be much appreciated if you could fill out the [pull request template](https://raw.githubusercontent.com/electron-userland/electron-packager/master/pull_request_template.md) and insert it into the PR summary.

**Pull request closed without merging**
