### PR TITLE
feat: add support for Mojave app notarization

### PR DESCRIPTION
**Pull request by MarshallOfSound**
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] The changes are appropriately documented (if applicable).
* ~[] The changes have sufficient test coverage (if applicable).~
* [x] The testsuite passes successfully on my local machine (if applicable).

**Summarize your changes:**
Functionality comes from [`electron-notarize`](https://github.com/electron-userland/electron-notarize)

We can't really add tests for this because it requires a legit apple ID and no CI system is updated to a high enough macOS / Xcode version to run tests 😆 

```js
// Example usage
package({
  osxSign: true,
  osxNotarize: {
    appleId: process.env.MY_APPLE_ID,
    appleIdPassword: process.env.MY_APPLE_ID_PASSWORD,
  }
})
```

### CODE REVIEW

**Comment by malept** [comment]
@MarshallOfSound this PR is dependent upon #900 due to the version of Node `electron-notarize` targets.

**Comment by malept** [comment]
> no CI system is updated to a high enough macOS / Xcode version to run tests :laughing:

What are the minimum macOS/Xcode versions? Travis added [Xcode 10.1](https://blog.travis-ci.com/2018-11-01-xcode-10-1-is-now-available) recently.

**Comment by malept** [comment]
@MarshallOfSound I added tests (and moved some code around in the process). Could you take a look to see that the tests are the expected behavior?

**Comment by MarshallOfSound** [comment]
@malept Seems legit to me, thanks for picking that up 👍

**Pull request merged**
