### PR TITLE
Add check for additional properties for better error reporting

### PR DESCRIPTION
**Pull request by kokarn**
**Summarize your changes:**
Minor logging update to correctly display what properties we look for when building.

Probably related to https://github.com/electron-userland/electron-packager/issues/476

EDIT: Sorry about the spam :/

### CODE REVIEW

**Comment by malept** [comment]
Thank you for the pull request, but could you be more specific about the impact of the change? How does this make for better error reporting? Please give an example of how the logging changes.

**Comment by malept** [comment]
_Additionally, in the future, making sure that all of the questions in the pull request template are answered would cut down on the amount of notification spam generated by your pull request._

**Comment by kokarn** [comment]
So sorry about the questions! Was thinking because they didn't really add any value it was safe to remove.

Currently when packaging from `C:\repos\my-app` with an invalid package.json missing electron & electron-prebuild as (dev)dependency this is the output
```sh
> electron-packager . --platform=win32 --arch=x64

Unable to determine application name or Electron version. Please specify an application name and Electron version.

For more infomation, please see
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#name or
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#version

Cannot find module 'package.json' from 'C:\repos'(Properties not found yet: dependencies.electron-prebuilt,devDependencies.electron-prebuilt)
```

With the changes this is the output
```
> electron-packager . --platform=win32 --arch=x64

Unable to determine application name or Electron version. Please specify an application name and Electron version.

For more infomation, please see
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#name or
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#version

Cannot find module 'package.json' from 'C:\repos'(Properties not found yet: dependencies.electron,devDependencies.electron,dependencies.electron-prebuilt,devDependencies.electron-prebuilt)
```

I'm aware it's a very minimal change but I believe it would help to remove some confusion for first time adopters as it did for me.

PS: I've filed a separate bug report for the incorrect path and ugliness of the output message

**Comment by malept** [comment]
Right now I don't think this is the right solution to the problem. Adding those entries causes unnecessary checking via the `get-package-info` module. I believe that the correct fix is the one described in https://github.com/electron-userland/electron-packager/issues/461.

Does the documentation in https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#version need to be updated to be more clear?

**Comment by kokarn** [comment]
Yeah you are probably correct in that.

Hmm, probably not. 

For a little while I mistook the version in package.json as the "version" it was referring to but that's probably just me being a bit hasty.

Let's hope for #461 instead.

**Comment by malept** [comment]
> For a little while I mistook the version in package.json as the "version" it was referring to

This kind of reaction is why I never liked the electron version option named "version". I think it should be named `electronVersion` (or `--electron-version` on the command line).

**Comment by kokarn** [comment]
It's kinda of weird, yeah. 

First impressions is a bit all over the place. 

The functionality is amazing but the mix & match between using custom props (productName), props with the same name (version) and default props (dependencies/devDependencies) makes it a bit confusing at first.

I think id actually prefer a custom dotfile just for electron-packager or something like that just to make it 100% clear.

**Comment by malept** [comment]
FWIW I'd like to move `productName` to a more standard place like https://docs.npmjs.com/files/package.json#config. I'd also like the ability to configure all (most?) of Electron Packager via the `config` section of `package.json`, but that would require more thought.

**Comment by malept** [comment]
> This kind of reaction is why I never liked the electron version option named "version". I think it should be named `electronVersion` (or `--electron-version` on the command line).

I've reopened #154 as a result.

**Comment by kokarn** [comment]
Great! Never heard of "Principle of least astonishment" but i totally agree with that sentiment.

**Pull request closed without merging**
