### PR TITLE
Add default values to arch and platform

### LINKED ISSUE #36: `--arch` should default to host arch
Good defaults again. Less config.

### PR DESCRIPTION
**Pull request by malept**
**Have you read the [section in CONTRIBUTING.md about pull requests](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#filing-pull-requests)?**

Yes

**Summarize your changes:**

The defaults are the host's arch and platform values.

Fixes #36.

**Are your changes appropriately documented?**

Updated NEWS, <ins>readme</ins>, API, & CLI docs. <del>I probably need to update the readme as well (have not done that yet).</del>

**Do your changes have sufficient test coverage?**

Changed the defaults test to test the new platform/arch defaults.

**Does the testsuite pass successfully on your local machine?**

Yes

### CODE REVIEW

**Comment by malept** [comment]
@kevinsawicki @jlord @zeke any comments/concerns you have on either the concept or the changes would be much appreciated. This one is likely going to be a fairly controversial change.

**Comment by kevinsawicki** [comment]
>  any comments/concerns you have on either the concept or the changes would be much appreciated.

My instinct is to keep 32-bit as the default arch instead of the host arch (which is presumably 64-bit since developers commonly use 64-bit machines). When unspecified, I'm assuming the person wants a package that will work on the most machines possible, and 32-bit will work more places than 64-bit.

For platform though, the host platform sounds like a great default that people will expect 👍

**Comment by malept** [comment]
My  rationale for making both defaults the same as the host is that it is easier for the developer to test. (I should have put that in the PR summary.)

I believe that Windows 32-bit executables will run on 64-bit machines (maybe? I could be wrong) but in order for Linux 32-bit executables to run, the whole 32-bit glibc/etc stack also needs to be installed (e.g., `dpkg --add-architecture i386`), unless for some reason Electron is statically linked to musl or similar :smile:

**Comment by kevinsawicki** [comment]
> I believe that Windows 32-bit executables will run on 64-bit machines 

Yup, that is my understanding as well.

> but in order for Linux 32-bit executables to run, the whole 32-bit glibc/etc stack also needs to be installed (e.g., dpkg --add-architecture i386)

Oh, interesting, didn't realize this.

Since it seems like the better default on Linux is the host arch, and their is no 32-bit on macOS, the host arch is the better default.

One question, if I am on 32-bit Linux and Windows, and I request to build for macOS with no arch specified, will it still build a 64-bit version of mac since their is no 32-bit, or would it error about 32-bit mac being unavailable?

**Comment by malept** [comment]
> One question, if I am on 32-bit Linux and Windows, and I request to build for macOS with no arch specified, will it still build a 64-bit version of mac since their is no 32-bit, or would it error about 32-bit mac being unavailable?

It will currently error. It would also error if #106 is fixed and you only specify `--arch=armv7l` on OSX/Windows.

**Comment by zeke** [comment]
Nice! Are you planning to land this in 8.0.0?

**Comment by malept** [comment]
Yup!

**Pull request merged**
