### PR TITLE
Bump electron-download to v2

### PR DESCRIPTION
**Pull request by quicksnap**
Does this work? Also, want me not to bump electron-packager to 5.2.2?

### CODE REVIEW

**Comment by malept** [comment]
Definitely do *not* bump electron-packager's version. The next version is 6.0.0 (see #266 for status).

**Comment by quicksnap** [comment]
Ok! This simply bumps electron-download now

**Comment by malept** [comment]
Looks good! Per the [pull request guidelines](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#filing-pull-requests), please squash the commits and I'll merge.

**Comment by quicksnap** [comment]
Roger! All done. Thanks!

**Pull request merged**
