### PR TITLE
Allow app to be built from already packaged ASAR

### PR DESCRIPTION
**Pull request by Ivshti**
This PR allows apps to be built from pre-packaged ASAR's.
The way it works with the CLI is simple: just pass the ASAR in place of the directory.
For programmatic usage, use "asar-package" arg.

Useful when building for a few platforms at once :)

### CODE REVIEW

**Comment by Ivshti** [comment]
Can we please bump & publish when this is merged? :)

**Comment by malept** [comment]
Could you rebase your commits as appropriate?

**Comment by Ivshti** [comment]
Done.

**Comment by kfranqueiro** [comment]
This should ideally include updates to the rest of the README to indicate that either `dir` or `asar-package` is now required.  (Currently it lists `dir` as required.)

**Comment by Ivshti** [comment]
Thanks for the tip, updated the documentation

**Comment by malept** [comment]
Is it possible to add a test for this?

Apart from that (and a further rebase), it seems like this can be merged.

**Comment by maxogden** [comment]
I agree a test is needed here so that we can catch regressions in the future

**Comment by malept** [comment]
It's been over 6 months since there's been any activity on this PR and it's very out-of-date. I still don't have any objections to adding this feature, however the following things need to be done before it's ready for review:

* Rebase the commits on master
* Instead of `opts['asar-package']`, there is now a merged `asar` set of options (as of #417) so it should be moved into `opts.asar.package`.
* Add at least one test

I'm closing this PR until someone volunteers to pick it up again.

**Pull request closed without merging**
