### PR TITLE
enable `asar` and `prune` options by default - fixes #35

### LINKED ISSUE #35: `--asar` and `--prune` should be enabled by default
I don't see why you wouldn't want those and I think most do. We could instead have `--no-asar` and `--no-prune` flags. I much prefer us to have sane defaults, which means less config mess for users.

### PR DESCRIPTION
**Pull request by sindresorhus**
// @malept @develar

### CODE REVIEW

**Comment by develar** [comment]
👍 asar is already default in the `electron-builder`. And it should be default because Window IO is very poor and asar helps a lot on Windows platform.

But please note — https://github.com/electron-userland/electron-builder/issues/351 (anyway, it is electron-builder responsibility to deal with it).

**Comment by malept** [comment]
A few general notes:

* This requires a major version bump.
* I don't think this sets either parameter by default for the CLI.
* This will conflict with #353. (And I want to take that one first because it should only require a minor version bump.)

**Comment by malept** [comment]
Also looks like there's at least one failing test.

**Comment by develar** [comment]
@sindresorhus In the next upcoming electron-builder 5 `prune` will be enabled by default if not two-package.json project structure is used.

**Comment by sindresorhus** [comment]
Closing this. I'm now using `electron-builder` which has `asar: true` by default. And I don't have the time to finish this PR.

**Pull request closed without merging**
